Release 5.7.0
voxpupuli/puppet-yum pull request #272
Opened 2022-08-03 17:47 UTC by bastelfreak

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2022-08-03 17:51 UTC, jcpunk approved these changes

2022-08-03 17:51 UTC, jhoblitt reviewed
Should this be a major API bump?  I'm concerned that #271 might cause breakage for someone.

2022-08-03 18:06 UTC, bastelfreak commented
indeed it's a breaking change

2022-08-03 18:12 UTC, jcpunk commented on metadata.json
> +  "version": "5.7.0",
Should this be 6.0.0 then?

2022-08-03 20:45 UTC, vchepkov approved these changes

2022-08-03 20:48 UTC, jhoblitt requested changes
CHANGELOG and the version need to be updated to `6.0.0`.

2022-08-04 06:55 UTC, bastelfreak commented on metadata.json
> +  "version": "5.7.0",
ups, updated it

2022-08-04 12:34 UTC, jhoblitt approved these changes
LGTM

2022-08-04 12:37 UTC, merged