Deploying multiple gpgkey in one repo
voxpupuli/puppet-yum pull request #278
Opened 2022-10-06 18:21 UTC by teluq-pbrideau

#### Pull Request (PR) description
The yum repository format should support entering multiple keys in the `gpgkey` entry, like the following entry for gitlab:
```
[gitlab_gitlab-ce]
name=gitlab_gitlab-ce
baseurl=https://packages.gitlab.com/gitlab/gitlab-ce/el/8/$basearch
repo_gpgcheck=1
gpgcheck=1
enabled=1
gpgkey=https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
       https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey/gitlab-gitlab-ce-3D645A26AB9FBD22.pub.gpg
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```
Currently, this module only deploy the first gpgkey it encounter.  This change allow to deploy multiples gpg keys (separated by any white spaces), for example:
```
class { 'yum' :
  managed_repos => ['gitlab'],
  gpgkeys       => {
    '/etc/pki/rpm-gpg/RPM-GPG-KEY-gitlab'                  => { source => 'https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey' },
    '/etc/pki/rpm-gpg/RPM-GPG-KEY-gitlab-3D645A26AB9FBD22' => { source => 'https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey/gitlab-gitlab-ce-3D645A26AB9FBD22.pub.gpg' },
  },
  repos         => {
    'gitlab' => {
      [...]
      'gpgkey' => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-gitlab file:///etc/pki/rpm-gpg/RPM-GPG-KEY-gitlab-3D645A26AB9FBD22',
    },
}
```

2022-10-06 18:55 UTC, teluq-pbrideau commented
I’m not sure, but does this PR fixes #116? It seems old

2022-11-08 21:57 UTC, jhoblitt requested changes
This seems reasonable to me. I think it is ready for merge with some minor reformatting.

2022-11-08 21:57 UTC, jhoblitt commented on spec/classes/init_spec.rb
> +        let(:params) { { managed_repos: ['example'], repos: { example: { baseurl: 'https://example.com', gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-example' } }, gpgkeys: { '/etc/pki/rpm-gpg/RPM-GP
The line length is excessive. Please reformat.

2022-11-08 21:57 UTC, jhoblitt commented on spec/classes/init_spec.rb
> +        let(:params) { { managed_repos: ['example'], repos: { example: { baseurl: 'https://example.com', gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-example file:///etc/pki/rpm-gpg/RPM-GPG-KEY-examp
The line length is excessive. Please reformat.

2022-11-08 21:57 UTC, jhoblitt commented on manifests/init.pp
> +                    before => Package[$utils_package_name],  # GPG Keys for any managed repository need to be installed before we attempt to install any packages.
I realize this is copied from the existing code but the trailing comment makes this line excessively long.

2022-11-09 15:43 UTC, jhoblitt commented on manifests/init.pp
> +                    before => Package[$utils_package_name],  # GPG Keys for any managed repository need to be installed before we attempt to install any packages.
I probably would have put it on the line above but I think it is acceptable as-is.

2022-11-09 15:43 UTC, jhoblitt approved these changes

2022-11-09 15:43 UTC, jhoblitt commented
This LGTM to me now. Thank you for contributing.

2022-11-09 15:43 UTC, merged